install:
	pip install pyinstaller
	pyinstaller --onefile arith.py
	mv dist/arith .
	find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +
	find . -name '__pycache__' -exec rm -fr {} +
